# Generated by Django 5.2.7 on 2025-11-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_passwordresetcode'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresetcode',
            new_name='accounts_pa_user_id_193f58_idx',
            old_name='accounts_pa_user_id_c6cbd5_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresetcode',
            new_name='accounts_pa_expires_d44861_idx',
            old_name='accounts_pa_expires_0e0fbf_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresetcode',
            new_name='accounts_pa_used_491bd9_idx',
            old_name='accounts_pa_used_01f660_idx',
        ),
    ]
