# Generated by Django 5.2.7 on 2026-04-26 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_passwordresetcode_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GateAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_username', models.CharField(blank=True, max_length=150)),
                ('gate_full_name', models.CharField(blank=True, max_length=255)),
                ('action_type', models.CharField(choices=[('login_success', 'Successful Login'), ('login_failed', 'Failed Login'), ('logout', 'Logout'), ('qr_scan_success', 'QR Scan Success'), ('qr_scan_denied', 'QR Scan Denied'), ('manual_entry', 'Manual Entry'), ('password_reset', 'Password Reset'), ('account_created', 'Account Created'), ('account_deactivated', 'Account Deactivated'), ('account_reactivated', 'Account Reactivated'), ('account_deleted', 'Account Deleted')], max_length=32)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('denied', 'Denied'), ('warning', 'Warning'), ('info', 'Info')], max_length=16)),
                ('performed_by_label', models.CharField(blank=True, max_length=255)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gate_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_gate_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['created_at'], name='accounts_ga_created_f564da_idx'), models.Index(fields=['action_type'], name='accounts_ga_action__7300fa_idx'), models.Index(fields=['status'], name='accounts_ga_status_bb4575_idx'), models.Index(fields=['gate_user', 'created_at'], name='accounts_ga_gate_us_0d3df1_idx'), models.Index(fields=['gate_username'], name='accounts_ga_gate_us_e833e0_idx')],
            },
        ),
    ]
