# Generated by Django 5.2.7 on 2025-11-01 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Attendance: switch name -> FK
        migrations.RemoveField(
            model_name='eventattendance',
            name='verified_by_name',
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_attendance', to=settings.AUTH_USER_MODEL),
        ),

        # Event: add capacity and registration window
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_close',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_open',
            field=models.DateTimeField(blank=True, null=True),
        ),

        # Registration: first drop old unique_together to remove index on resident_name (SQLite-friendly)
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together=set(),
        ),

        # Then add FK resident, drop old resident_name, and recreate unique constraint
        migrations.AddField(
            model_name='eventregistration',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='resident_name',
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('event', 'resident')},
        ),
    ]
