# Generated by Django 5.2.7 on 2025-11-02 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_event_date_idx_event_event_type_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['updated_at'], name='event_updated_idx'),
        ),
    ]
