# Generated by Django 5.2.7 on 2026-04-21 11:51

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_VENUES = [
    ("Function Hall", 50),
    ("Barangay Hall", 25),
    ("Sacred Heart", 50),
    ("Hospicio Quadrangle", 300),
    ("St. Joseph Hall", 50),
    ("Court", 300),
]


def seed_venues(apps, schema_editor):
    Venue = apps.get_model("events", "Venue")
    Event = apps.get_model("events", "Event")

    venues_by_name = {}
    for name, max_capacity in DEFAULT_VENUES:
        venue, _created = Venue.objects.get_or_create(
            name=name,
            defaults={"max_capacity": max_capacity, "is_active": True},
        )
        venues_by_name[name.casefold()] = venue

    existing = (
        Event.objects.exclude(venue="")
        .values("venue", "capacity")
        .distinct()
        .order_by("venue")
    )
    for row in existing:
        name = (row.get("venue") or "").strip()
        if not name:
            continue
        key = name.casefold()
        capacity = row.get("capacity") or 1
        venue = venues_by_name.get(key)
        if venue is None:
            venue, _created = Venue.objects.get_or_create(
                name=name,
                defaults={"max_capacity": capacity, "is_active": True},
            )
            venues_by_name[key] = venue
        Event.objects.filter(venue__iexact=name, venue_ref__isnull=True).update(venue_ref=venue)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_expand_event_audience_type_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('max_capacity', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='venue_name_idx'), models.Index(fields=['is_active'], name='venue_active_idx')],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='venue_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.venue'),
        ),
        migrations.RunPython(seed_venues, migrations.RunPython.noop),
    ]
