# Generated by Django 5.2.7 on 2026-03-03 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conflictlog',
            new_name='sync_confli_created_8a6192_idx',
            old_name='sync_conflict_created_idx',
        ),
        migrations.RenameIndex(
            model_name='conflictlog',
            new_name='sync_confli_event_t_1c5916_idx',
            old_name='sync_conflict_event_idx',
        ),
        migrations.RenameIndex(
            model_name='conflictlog',
            new_name='sync_confli_aggrega_a859ba_idx',
            old_name='sync_conflict_agg_idx',
        ),
        migrations.RenameIndex(
            model_name='outboxevent',
            new_name='sync_outbox_created_cbb678_idx',
            old_name='sync_outbox_created_idx',
        ),
        migrations.RenameIndex(
            model_name='outboxevent',
            new_name='sync_outbox_sent_at_91f25c_idx',
            old_name='sync_outbox_sent_idx',
        ),
        migrations.RenameIndex(
            model_name='outboxevent',
            new_name='sync_outbox_event_t_c4dc24_idx',
            old_name='sync_outbox_event_idx',
        ),
        migrations.RenameIndex(
            model_name='outboxevent',
            new_name='sync_outbox_aggrega_ae2b68_idx',
            old_name='sync_outbox_agg_idx',
        ),
    ]
