# Generated by Django 5.2.7 on 2025-11-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0005_gender_field'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='verificationrequest',
            new_name='residents_v_status_87b15b_idx',
            old_name='residents_v_status_d3cf3d_idx',
        ),
        migrations.RenameIndex(
            model_name='verificationrequest',
            new_name='residents_v_created_19ba45_idx',
            old_name='residents_v_created_fa34d4_idx',
        ),
    ]
