# Generated by Django 5.2.7 on 2026-02-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0006_rename_residents_v_status_d3cf3d_idx_residents_v_status_87b15b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_gate_operator',
            field=models.BooleanField(default=False),
        ),
    ]
