# Generated by Django 5.2.7 on 2026-04-16 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0010_residentprofile_deactivation_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='residentprofile',
            name='residents_r_archived_d02e8a_idx',
        ),
        migrations.RemoveIndex(
            model_name='residentprofile',
            name='residents_r_archive_f04010_idx',
        ),
    ]
