# Generated by Django 5.2.7 on 2026-04-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0012_resident_category_and_voter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentprofile',
            name='voter_status',
            field=models.CharField(choices=[('registered_voter', 'Registered Voter'), ('not_yet_voter', 'Not Yet Voter'), ('other_area_voter', 'Voter in Other Barangay / Other Area'), ('unspecified', 'Unspecified')], default='unspecified', max_length=20),
        ),
    ]
