# Generated by Django 5.2.7 on 2026-04-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0013_alter_residentprofile_voter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentprofile',
            name='resident_category',
            field=models.CharField(choices=[('resident', 'Resident'), ('client', 'Client')], default='resident', max_length=20),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='voter_status',
            field=models.CharField(choices=[('registered_voter', 'Registered Voter'), ('not_yet_voter', 'Not Yet Voter'), ('unspecified', 'Unspecified')], default='unspecified', max_length=20),
        ),
    ]
