# Generated by Django 5.2.7 on 2026-04-16 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auditlog_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adminsetting',
            new_name='common_admi_key_b38e65_idx',
            old_name='common_admi_key_9cb456_idx',
        ),
        migrations.RenameIndex(
            model_name='adminsetting',
            new_name='common_admi_updated_1184b3_idx',
            old_name='common_admi_updated_c3a95d_idx',
        ),
        migrations.RenameIndex(
            model_name='guestappointment',
            new_name='common_gues_eta_1e5a3f_idx',
            old_name='common_gues_eta_bce93a_idx',
        ),
        migrations.RenameIndex(
            model_name='guestappointment',
            new_name='common_gues_status_701392_idx',
            old_name='common_gues_status_17ae15_idx',
        ),
        migrations.RenameIndex(
            model_name='guestappointment',
            new_name='common_gues_created_5fef89_idx',
            old_name='common_gues_created_c18359_idx',
        ),
        migrations.RenameIndex(
            model_name='guestappointment',
            new_name='common_gues_qr_toke_2e4342_idx',
            old_name='common_gues_qr_toke_dfbca2_idx',
        ),
        migrations.RenameIndex(
            model_name='guestappointment',
            new_name='common_gues_checked_3c86e1_idx',
            old_name='common_gues_checked_6ae95b_idx',
        ),
        migrations.RenameIndex(
            model_name='guestappointment',
            new_name='common_gues_checked_ef661a_idx',
            old_name='common_gues_checked_84d2ff_idx',
        ),
        migrations.RenameIndex(
            model_name='guestappointment',
            new_name='common_gues_archive_ee7f95_idx',
            old_name='common_gues_archived_4d54cf_idx',
        ),
        migrations.RenameIndex(
            model_name='guestappointment',
            new_name='common_gues_archive_93b62b_idx',
            old_name='common_gues_archive_a14280_idx',
        ),
        migrations.RenameIndex(
            model_name='guestappointmentscanlog',
            new_name='common_gues_created_717189_idx',
            old_name='common_gues_created_f921fd_idx',
        ),
        migrations.RenameIndex(
            model_name='guestappointmentscanlog',
            new_name='common_gues_directi_6fdda7_idx',
            old_name='common_gues_directi_4fc95f_idx',
        ),
        migrations.RenameIndex(
            model_name='guestappointmentscanlog',
            new_name='common_gues_method_e3405c_idx',
            old_name='common_gues_method_148b8f_idx',
        ),
    ]
