# Generated by Django 5.2.7 on 2026-04-27 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_rename_common_admi_key_9cb456_idx_common_admi_key_b38e65_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=160)),
                ('appointment_at', models.DateTimeField()),
                ('resident_note', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident_appointments', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_appointments_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-appointment_at', '-created_at'],
                'indexes': [models.Index(fields=['resident', 'created_at'], name='common_resi_residen_43d80f_idx'), models.Index(fields=['status'], name='common_resi_status_df8868_idx'), models.Index(fields=['appointment_at'], name='common_resi_appoint_68f146_idx'), models.Index(fields=['created_at'], name='common_resi_created_f3300b_idx')],
            },
        ),
    ]
